### ISSUE TITLE
Use the push-based webhook api of GitHub

### ISSUE THREAD

**Issue by erwinvaneyk** [erwinvaneyk/github-notify#4]
Currently we pull on intervals. Besides that this causes unnecessary requests to the GitHub API and delays in the notifications, it also causes problems such as #3.

Switching to make use of a webhook should be possible for the notifications, by using the events api and [issue api](https://developer.github.com/v3/issues/events/)

**Comment by trensen** [comment]
Yes, that would be nice indeed. However, you have to add such webhook to every repo / organisation you want to track... In larger organisations this isn't appreciated I guess. :stuck_out_tongue_closed_eyes:
Let's stick with pull-based notifications for now.
